### ISSUE TITLE
Dirt Rally jittery after SteamVR update

### ISSUE THREAD

**Issue by FSatmar** [LibreVR/Revive#1121]
Hi,
I am playing DirtRally on WMR and Revive 1.6.0.3. After the latest update to the stable branch of SteamVR (1.1.3) I got very poor performance in DirtRally. The head movement is very jittery and changing the settings does not make any difference. Before the update it was running fine. Is there anything that can be done in Revive to fix this?

**Comment by flowerdealer** [comment]
Same here, all Revive games are completely broken now.

**Comment by jonnypanic** [comment]
Yep, same here on WMR, all revive games distorted and jittery, and in remixed games just crash.

**Comment by rtamotorsports** [comment]
I can report the same Samsung Odyssey user, Nvidia 1080ti latest steam VR and updated revive to 1.6.1, i can only run in very low preset and i even purchased the Oculus version and discovered that remix isn't supported yet on that title.

**Comment by Pitrakos** [comment]
Solution found:

Jackatack:
Jackatack:
This can be complicated for some users so I did the job for you :)

https://drive.google.com/file/d/1QGS8v36mrh7COTDNgDv2fLW1H1LF4Eve/view?usp=sharing

Everything is downloaded in this archive, you just have to delete the folder "SetamVr" (steam / steam apps / common / steamVr) & replace it with that of the archive and you will come back to the version before the cursed 1.1. 3.
In the event of a forced update, simply delete the SteamVr folder and put the archive folder back.

Good game to all

Also use revive 1.5.

**Comment by pawelkusmierek** [comment]
Umm I do not have a SteamVR folder under steam apps/common in any of my steam libraries. Also steamVR no longer appears on the list of installed games/software in steam, it's started from a buttom in upper right corner. Could it be that from 1.1.4 they have integrated it into the application?

**Comment by pawelkusmierek** [comment]
@nbates66 
Yes, I should have added that I found it. I forgot that in addition to steam libraries on D: and E: where I keep my games I also have the default library on C: and there it was. Still I haven't got to trying the fix, spending more time in racing games that work without it. I guess I am a bit apprehensive that the fix may fix Dirt Rally but ruin the other games which depend on SteamVR, lie Assetto Corsa

**Comment by wotever** [comment]
ive tried reporting it to steam. ive posted a few threads in the steam vr section. but the above solution by pitrakos worked for me. dirt rally now works fine again. and all other games seem fine too. so im happy for now. wish steam vr would stop releasing buggy updates though. and give an official solution for rolling back to last update if the new one is buggy. steam vr always seems to overlook dirt rally and its my favourite game vr and non vr... i barely even play other games. a bit of assetto corsa/ project cars vr. and some occasional onward/ pavlov and thats pretty much it..

**Comment by Raging-Beard** [comment]
No change after recent update to 1.2.7 or whatever :(

**Comment by Raging-Beard** [comment]
1.2.10 still no fix :(

**Comment by flowerdealer** [comment]
Does the latest version of Revive help anything?

**Comment by Raging-Beard** [comment]
Sadly not, no difference.

**Comment by jonnypanic** [comment]
I just managed to play a reasonably enjoyable race on SteamVR 1.2.10. Unfortunately I had to put all my settings through the floor to get rid of the jitter, but it worked. I used SteamVR Advanced Settings to lower rendertarget to 0.9, with WMR autoreprojection turned off (it seems to be broken recently), and 1.0 rendertarget in the WMR driver settings, everything important on Ultra Low in Dirt Rally. It's annoying to have to do that of course, but for now I am just happy playing Dirt again. 

It seems that the SteamVR updates have just been messing up performance horribly on Revive. There are a lot of Vive users with similar complaints on the Steam forums. 

What specs are you guys/girls using? 
I use an i5 8400, GTX 1060 3gb, 16gb ram, Dell Visor

**Comment by ilimo** [comment]
I have this tracking delay in my headset with 1.2.10. Any way to fix this. Its as if the entire view is wobbling in my pimax 5k+ when my head moves around

**Comment by wotever** [comment]
just use the above solution. its an older version of steam vr but honestly who cares? its not like steam vr updates or updates for anything in general usually add new features or fix bugs/ performance increases these days. updates typically break more than they fix.

the above worked for me. simply delete or copy/ backup your old steam vr folder and replace with the steam vr from the above download. it works. with wmr reprojection on or off. still workds. although lately ive had best performance with reprojection set to auto and only important graphics set to high/ ultra. most to medium/ low. and i honestly prefer no ss and no msaa etc in this game. i prefer the extra sharpness even at the cost of more jaggies. and i get great super smooth performance with no judder/ stutter. dirt rally vr is the best games ever, and now dirt rally 2.0 has announced vr support for a later release! oculus exclusive again unfortunately, but revive should work fine and something is better than nothing. and maybe remixed will be working better by then so we can bypass revive/ steam vr entirely!
i have not been able to get remixed working myself at all yet though i must admit. at least not with dirt rally which is the only game i have tried remixed with so far.

all you are supposed to have to do is close steam. manually open revive overlay, have mixed reality portal open then laucnh game, right? and that should launch it in native wmr bypassing steam vr?

sounds awesome if it gets more reliable etc.

p.s - the dev of revive/ remixed is awesome. absolute legend!

**Comment by wotever** [comment]
illmo yeah, thats the problem steam vr updates added late last year to revive games or at least dirt rally. using an older version of steam vr fixes this. possibly lowering your settings or having better hardware might fix it too. and manually turning wmr reprojection to auto in its config file works quite well in dirt rally too

i guess it could also be a pimax specific problem. try lowering your fov if you havnt already using the pitool software i dont know anything about pimax though, other than im jealous. im using a lenovo explorer myself.

i cant recommend doing this enough:

https://drive.google.com/file/d/1QGS8v36mrh7COTDNgDv2fLW1H1LF4Eve/view?usp=sharing

its from 'Pitrakos'. his comment and this link is above. i just reposted it because it is that good. it is simple and it works. if you really want you can switch between them so you can have the latest steam vr for other games, just keep both steam vr folders. it sucks that steam vr devs havnt fixed this in the last 3-4 months or so since they created the issue. oh well. hopefully someone will post here when/if it is fixed.

**Comment by Raging-Beard** [comment]
Does SteamVR not just auto update itself again, or how do you stop it from doing so?

**Comment by wotever** [comment]
raging beard yeah thats what i though would happen, but no, the guy that created/ edited this version of steam vr must have added something so it always thinks its up to date. i have been using it for the last few months with no issue. other than i went to play onward last week and its easy anti cheat kept booting me, only realising now it could have been the steam vr folder, easy fix, just copy original steam vr back accross before i play onward, and let any steam vr updates download. i had just reinstalled windows at the time because the windows 10 1809 ( october update) was causing me problems and i thought it was microsofts fault somehow..

**Comment by wotever** [comment]
pitrakos also says to use revive 1.5 but i have not had any issues keeping revive up to date so i dont bother with that myself

**Comment by ilimo** [comment]
> illmo yeah, thats the problem steam vr updates added late last year to revive games or at least dirt rally. using an older version of steam vr fixes this. possibly lowering your settings or having better hardware might fix it too. and manually turning wmr reprojection to auto in its config file works quite well in dirt rally too
> 
> i guess it could also be a pimax specific problem. try lowering your fov if you havnt already using the pitool software i dont know anything about pimax though, other than im jealous. im using a lenovo explorer myself.
> 
> i cant recommend doing this enough:
> 
> https://drive.google.com/file/d/1QGS8v36mrh7COTDNgDv2fLW1H1LF4Eve/view?usp=sharing
> 
> its from 'Pitrakos'. his comment and this link is above. i just reposted it because it is that good. it is simple and it works. if you really want you can switch between them so you can have the latest steam vr for other games, just keep both steam vr folders. it sucks that steam vr devs havnt fixed this in the last 3-4 months or so since they created the issue. oh well. hopefully someone will post here when/if it is fixed.

Well I have a 2080Ti, 8700k, 32gb, so its not the hardware... If I download this SteamVR, how do I install it so it reverts back, and does this stop updating steamVR as @wotever said below?

**Comment by Raging-Beard** [comment]
Awesome thanks will try.

@wotever regarding Onward, I had that too despite being on latest SteamVR. To solve it I went to Onward/EasyAntiCheat folder and ran the setup exe. I believe it was Devs on Steam who suggested it, can't remember.

**Comment by wotever** [comment]
wow.. a 2080ti??! im using a gtx 1060 and i get perfectly good performance in dirt rally wtih reprojection on auto and texture ultra, track utltra cars high, ground cover high, reflections medium, shadows low, most other settings medium/ low etc. admittedly using wmr reprojection idicator i am usually getting dark blue which means reprojeciton active and gpu limited. sometimes light blue which means reprojection active cpu limited. green means reprojection off 90fps.

its feels perfectly smooth to me though. and with reprojection set ot off i can still get smooth fps with most settings on medium/ low. the key is using an old version of steam vr before they messed it up.

if you use the above link it should not auto update itself. it didnt for me. but you may want to switch steam vr folders/ versions depending on game.

@raging beard ah ok, thanks i will try that. makes sense as i reinstalled windows and kept old backup of game. so makes sense that the easy anti cheat would need to be reinstalled etc.

**Comment by ilimo** [comment]
> wow.. a 2080ti??! im using a gtx 1060 and i get perfectly good performance in dirt rally wtih reprojection on auto and texture ultra, track utltra cars high, ground cover high, reflections medium, shadows low, most other settings medium/ low etc. admittedly using wmr reprojection idicator i am usually getting dark blue which means reprojeciton active and gpu limited. sometimes light blue which means reprojection active cpu limited. green means reprojection off 90fps.
> 
> its feels perfectly smooth to me though. and with reprojection set ot off i can still get smooth fps with most settings on medium/ low. the key is using an old version of steam vr before they messed it up.
> 
> if you use the above link it should not auto update itself. it didnt for me. but you may want to switch steam vr folders/ versions depending on game.
> 
> @raging beard ah ok, thanks i will try that. makes sense as i reinstalled windows and kept old backup of game. so makes sense that the easy anti cheat would need to be reinstalled etc.

I'll try this one and see if it works better. Thanks guys!

**Comment by wotever** [comment]
@ilimo  to reinstall official steam vr its as simple as either deleting the one you download here and steam will redownload the official latest version. of keeping the old folder and switching it back, then if there are any updates steam will download them and next time you switch back to the official steam vr folder it will have the updates you downloaded still. if needed then you may need to right click on steam vr in your library go to properties go to local files and click on verify inegrity of game files.

**Comment by wotever** [comment]
report back if it works. it worked for me so hopefully it will work for you guys, and if it does it could be helpful to others to see.

**Comment by ilimo** [comment]
> report back if it works. it worked for me so hopefully it will work for you guys, and if it does it could be helpful to others to see.

I have SteamVR 1.2.10 - i downloaded the 1.1.3 version in that link, overwrote the files, opened steamVR and it's back to 1.2.10. What do I do?

**Comment by Raging-Beard** [comment]
I have numerous games set at various SS, is there a file I can copy from my current folder and drop in to this rollback to keep all those settings? Thanks

**Comment by ilimo** [comment]
It didnt overwrite the files. I just did it again and it seems to work. But now the window for Dirt Rally is below to my right.

**Comment by wotever** [comment]
hmmm when i launch steam vr and click on the steam vr drop down list, then on help then about steam vr
it says 'built oct 10 2018 at 4:57 version 1539100633"

so i dont know sorry. mine just works. i did nothing special. just deleted old folder and pasted new one. i had closed steam in the background while doing so...

**Comment by ilimo** [comment]
OH MAN IT WORKS! I just reset the view. Awesome thank you guys!

**Comment by wotever** [comment]
no worries. there is a recenter key to asign to your wheel/ gamepad in dirt rally's settings mine always starts like that too. you have to wait until you have gotten past the start screen before you can recenter though.

**Comment by wotever** [comment]
@raging beard shoot no idea sorry, hopefully someone else that knows their stuff can answer.. otherwise try googling for location of steam vr ss presets config file or somethign..?

**Comment by wotever** [comment]
@illimo thats great! i love dirt rally vr. enjoy! im jealous you get to play this game with a pimax 5k + though, ;-)

**Comment by ilimo** [comment]
> @Illimo thats great! i love dirt rally vr. enjoy! im jealous you get to play this game with a pimax 5k + though, ;-)

Ye it looks good so far. Thank you guys. Except the locked to horizon thing. Thats a bit weird, but all else is perfectly tracking and all.

**Comment by wotever** [comment]
you can change the locked to horizon cant you? with the vehicle camera motion setting or something like that.. it can apparently make some people a bit motion sick but it works fine for me. so you look down going down hills, up going up etc. jostles you around more and makes it more fun i think. assuming this is what you are talking about anyway..

**Comment by ilimo** [comment]
> you can change the locked to horizon cant you? with the vehicle camera motion setting or something like that.. it can apparently make some people a bit motion sick but it works fine for me. so you look down going down hills, up going up etc. jostles you around more and makes it more fun i think. assuming this is what you are talking about anyway..
I wasnt aware. Still new to it so i dont know all the settings. Thanks for the heads up ill play with the camera

**Comment by Raging-Beard** [comment]
AAARRRGGHHH even after using that rollback performance is terrible. Used to be great. Tried reinstall of DR and SteamVR, no change. Every other game/sim still work perfectly.
1080ti, i7 8700k, Vive Pro.

No idea what the issue can be. Even with settings right down low it's bad. It's like the FPS is good it just keeps dropping frames, if that makes sense.

**Comment by Raging-Beard** [comment]
Well after all that, turns out if I just turn off my USB converted Fanatec McLaren rim, FPS jumps up to 89-90 with no drops!

I am back on latest SteamVR full release and runs smooth.

Only issue now is my shifter isn't being seen by DR. Had this before but for the life of me I can't remember how I fixed it...

**Comment by wotever** [comment]
strange, glad you fixed it then, awesome that it works on the latest version of steam vr for you too.  hope you fix your shifer issue. i used to have my g29 wheel detected as a gamepad in dirt rally with terrible ffb etc. the only fix was strangely to unninstall geforce experience for me.

**Comment by rtamotorsports** [comment]
The only fix i found that works is what Pitrakos posted again thank you so much! @Pitrakos.

I'm on aryzen 2700x 16 gb ram and 2080ti

**Comment by Armada651** [comment]
Jitter issues have been fixed in the latest pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0

**Comment by flowerdealer** [comment]
I'm still seeing jitter on Dirt Rally (steam version) on the latest. I didn't repatch though, should I? Also, not sure how to launch the game without steamVR as it doesn't appear under the remixed launcher.

**Comment by Armada651** [comment]
You need to repatch or you won't see any changes.

**Comment by flowerdealer** [comment]
Sso it shouldn't matter if I launch through SteamVR then? Thanks for the fix btw and all your work.

**Comment by Armada651** [comment]
Patched games can be run through Steam, Revive even adds Oculus games to your Steam library, the Revive launcher is extra.

**Comment by makos101** [comment]
I can't get Dirt rally to even start currently. It says connecting to the game than just goes to the steam home screen. I followed these steps 

"https://www.reddit.com/r/WindowsMR/comments/aov0mv/dirt_rally_wmr_how_i_finally_it_it_working_with/"  

and even rolled back my revive and steam VR. Is anyone else having any luck?

**Comment by D2lod** [comment]
> report back if it works. it worked for me so hopefully it will work for you guys, and if it does it could be helpful to others to see.

Hey, I have been trying to use the old SteamVR folder. It will not let me use it without updating. For the few times it has started working and not been recognized by steam as out of date, it either crashes to a grey no-tracking screen, or it does load into VR, but the grey circle lines are missing from the environment. It's just a black space with lighthouses floating. No games will launch in the headset, and the library isn't in the menu, because SteamVR doesn't appear to be running all the way.

Are you still able to get Dirt Rally running? Have they made updates forced since you posted? 

I believe the performance problems with Dirt Rally are caused by the new reprojection setting. With the old settings (asynchronous, interleaved, and always on), I could find a combination that would work and didn't have a double image. Those settings were replaced with a single asynchronous reprojection setting, and it causes the double image problem. 

Turning that setting off now causes black flickering in my headset along with regular purple lines of judder on my performance chart, labeled on the legend as "display error". This judder is not performance-related. 

Steam's new reprojection screwed up the only way people had of getting around the double-image reprojection issue Dirt Rally with Revive has, while creating new random judder with asynchronous off.

So yeah, I am curious about whether you or anyone can play the game anymore.
