### ISSUE TITLE
Drop Dead multiplayer doesn't work (Vive)

### ISSUE THREAD

**Issue by Fixkey** [LibreVR/Revive#1223]
### Description of the issue
*Please provide us with a detailed description of the issue*
Going into multiplayer (both lobby and match) makes the whole game lag for about 4-5 seconds after that 2 seconds of normal gameplay and the lag loops back. (During the lag screen freezes and I'm moved into SteamVR place) apart from that multiplayer is working. I could start a game with someone but the huge lag was still there and after some time stuttering also kicks in.
Going back to single-player mode fixes the problem and no lags occur until going back to Multiplayer mode.

### Technical Information
*Tell us your specs and versions*
  - CPU: i7 6700k
  - GPU: gtx 1080
  - RAM: 16GB DDR4
  - OS: Windows 10 Pro 
  - Vive

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version 1.4.18
  - Revive installation version: 1.6.4.0

#### What is the last working version before this issue first came up?
  - Revive installation: N/A
  - SteamVR (unless remixed): N/A

### What apps/games are you trying to run?
  - Drop Dead

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Start Drop Dead game.
  2. Go to the main menu (by holding menu button)
  3. Press anything multiplayer related (Quick match/Create lobby/Check invites)

## Error messages/codes
  - N/A

**Comment by ORGATHM** [comment]
same here.
all multiplayer things are openening the "circle on bottom room", with the dropdead loading logo in front.
then it goes back into the started game session for 0.5 - 1 second, then the circle room appears again for 8-10 sec.
and so on in a loop.
the "circle room" interrupts the game continously.
when the other player leave the session, i am right in the game, but the grafix is smearing.
i think i see 4-5 last frames as a shadow (like an accoustic echo). unplayable.
revive 1.7.03, newest nvidia driver, steam and all games are up to date.
best regards

**Comment by KuraiKitsune** [comment]
Adding mine here too. Some friends recently got the Oculus Quest, and it would be awesome to play with them on my Vive. This game is fun.

Technical Information
CPU: Intel i7-5820K
GPU: GTX 1080
RAM: 32GB DDR4
OS: Windows 10 Pro x64
HTC-Vive


Versions and features
SteamVR version 1.5.16
Revive installation version: 1.7.1 pre-release
Oculus app version: 1.39.0.268010

**Comment by ORGATHM** [comment]
nobody hear us. its so sad. i want to play with my girl friend in coop mode but revive couldnt handle it.

**Comment by ORGATHM** [comment]
with 1.8.1 drop dead in multiplayer mode(in the menu+game) lost head tracking and after lost headtracking the room with the circles appears for a second. then the tracking comes back and the multiplayer menu comes back.
all in all, it seems it is better then before, but it does not work.
please check and fix it, i want to play with my girlfriend online. :-)

**Comment by kawatschaki** [comment]
Same Problem here, even when the game is started directly out of PiTool.

So either they are using the same method to connect to the Oculus service like Revive or the problem has something to do with the game itself.
If you take a look at the process in task manager you can see the drops in CPU load every few seconds... no idea why it behaves so strangely when you open up the multiplayer part... maybe it's timing out while constantly checking something in your Oculus friends list...

Did anyone come up with a solution/workaround yet or even tried getting in touch with the developer?

Cheers.

**Comment by kawatschaki** [comment]
Same Problem here, even when the game is started directly out of PiTool.

So either they are using the same method to connect to the Oculus service like Revive or the problem has something to do with the game itself.
If you take a look at the process in task manager you can see the drops in CPU load every few seconds... no idea why it behaves so strangely when you open up the multiplayer part... maybe it's timing out while constantly checking something in your Oculus friends list...

Did anyone come up with a solution/workaround yet or even tried getting in touch with the developers?

Cheers.

**Comment by ORGATHM** [comment]
in the last day i detected suspicios behavior with beat saber.
the same problem like in drop dead multiplayer.
if i moved my head, the game interrupts and jumps into the bottom circle view, and then back.
i fixed the beat saber problem after fresh install of win10.
but drop dead has got this strange behavior. no fix.
**for me it seems like the head moving/tracking data goes wrong into the pipe.**
maybe drop dead expects less data, or other formated data, what ever.
actually, the head moving is the root of the pain. that must be fixable :-)

**Comment by Armada651** [comment]
This is a known issue due to a missing hearbeat to the Oculus servers. However thanks to Nero a solution is being worked on.

**Comment by KuraiKitsune** [comment]
Revive v2.0 unfortunately did not resolve Drop Dead multiplayer

**Comment by jwalton314** [comment]
Feb 12, 2021. Still an issue.

**Comment by KsirHealer0** [comment]
I have a intel i7 with 32g ram and an nvidia rtx 3080 , I think this is “Bad Boy” enough to support the game but it does basically what everyone else is describing , we have hp reverb g2 headsets and also oculus quest 2 so we both want the extremely greater graphics quality of the reverb but it won’t run it stutters then the steam be box appears woth the game logo please wait and then stabilize half a second back flicker and stutter single player no problems at all .
