### ISSUE TITLE
Defector Not Working // ASSERTION FAILED // all other games work

### ISSUE THREAD

**Issue by forestgamer007** [LibreVR/Revive#1266]
For some reason, whenever I try to start defector, an error message pops up saying assertion failed. C++ Error.

  - CPU: Intel Core i7-6700K CPU
  - GPU: Geforce GTX 1070
  - RAM: 16384MB RAM 
  - OS:  Windows 10 64-bit
                 HTC Vive

Error when starting Revive. In the newest beta version on steam 1.5.16
Don't know what the issue is since I see others playing the game fine on Revive.

  - Revive installation: Newest Beta
  - SteamVR (unless remixed): 1.5.16

  1.  All I did was buy the game and tried to start playing on the NEWEST RELEASE. Since it didn't work I tried going on the NEWEST BETA and it still didn't work. After that, I entered the beta program on steamvr and I started the game again. This time, the game started, but it would not show up on headset just on the computer. Since then, I went back to normal steamvr and kept my Revive program on the newest beta. Hope someone can help because it's a big hassle when my other games work, but this one doesn't. Here is my error message.

![IMG_0273](https://user-images.githubusercontent.com/52846958/61167173-7ef7c800-a508-11e9-897e-da955566bd0f.jpg)

**Comment by Armada651** [comment]
Fixed in 1.7.2

**Comment by forestgamer007** [comment]
Hey, the game still isn't working on 1.7.2. The game shows on my monitor and looks choppy and doesn't play on my headset. it just says wrong video card next to steam vr. Once again, all other games work so I do not know what the problem is. Hope you can help. Also, I tried it in 1..8 but that didn't work either.
