### ISSUE TITLE
Controller bindings in SteamVR do not have any effect in revive games.

### ISSUE THREAD

**Issue by jsondag** [LibreVR/Revive#1283]
# Revive Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*
Controller bindings in SteamVR do not have any effect in revive games.

### Technical Information
*Tell us your specs and versions*
  - CPU: i7 9700K
  - GPU: RTX 2070 Super
  - RAM: 16G DDR4 3600
  - OS: Windows 10 x64
  - Valve Index

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version (unless Remixed): 1.6.10
  - Revive installation version: 1.7.1

#### What is the last working version before this issue first came up?
  - Revive installation: Unknown
  - SteamVR (unless remixed): Unknown

### What apps/games are you trying to run?
  - In death

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Added bindings for grip force to be higher to allow resting hands on the controller without triggering grip. No change
  2. Removed all grip bindings, no effect. Still grips at the lightest touch of the grip.
  2. Bindings work in native SteamVR games.

## Error messages/codes
  - N/A

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Are you sure you're removing the correct bindings? The grip is known as HandTrigger for the Oculus Touch

**Comment by jsondag** [comment]
Yes, I remove the rhandtrigger bindings under the grip heading for the index controller, in controller bindings for "In Death on Oculus", which I got to by selecting it from the top of the list on recent games, while I was playing it. I also reset Steam VR, and restarted the game, and went in to make sure the controller binding were still applied (they were). Changing the same setting on a steam game allowed me to disable, or reassign the right grip, and it took effect immediately in game.

**Comment by Armada651** [comment]
Found the cause of the issue: 682480ae742aa23fea3621bc618c7f506ebf9036

The fix will be available in the next release.

**Comment by Armada651** [comment]
Fixed in the latest release, though you may need to reset any custom bindings you've made.

**Comment by jsondag** [comment]
This doesn't seem to be fixed after I updated. I still have the binding selected to not have anything assigned to grip, and grip still acts like the righthandtrigger on the slightest touch. I also cannot select the default bindings. If I select view the default, then choose select this binding, my saved binding without grip actions is still the selected binding.

**Comment by Armada651** [comment]
That's a known bug, instead of selecting the default bindings save them as your personal binding.
