### ISSUE TITLE
Revive 1.8.0+ Controllers are not working on game load

### ISSUE THREAD

**Issue by mjsell123** [LibreVR/Revive#1311]
**Describe the bug**
I am attempting to use Revive 1.8.0+ on my Valve Index and every time I try to load a game it just gives a popup of "Failed to load action manifest, input will not function correctly!".  If the game then loads - no controllers are present.  If I back down to Revive 1.7.3 then everything works perfectly.

**To Reproduce**
1. Install Revive 1.8.0+
2. Open Revive, Oculus, and Steam VR
3. Try to launch a game through the Revive menu

**Expected behavior**
No error messages - controllers operational in game

**Environment (please complete the following information):**
 - App: All of the default Oculus apps available with a new Oculus account
 - OS: Windows 10
 - Headset: Index

**Versions (please complete the following information):**
 - Revive: 1.8.0
 - SteamVR: beta 1.7.6

**Additional context**

**Comment by Armada651** [comment]
Good find! I've changed the registry keys to use `HKEY_LOCAL_MACHINE` instead thereby side-stepping this issue.

Fixed in the latest version: https://github.com/LibreVR/Revive/releases/latest

**Comment by dungto789** [comment]
So i installed Defector, and this bug still exist in Revive 2.0.0, had to roll back to 1.7.1 to it worked ( didn't try 1.7.3 tho )
