### ISSUE TITLE
Games will not launch, Revive Tab in VR shows empty Window.

### ISSUE THREAD

**Issue by rad4Christ** [LibreVR/Revive#153]
I see revive's processes running, and whether I run as admin or not, no games show up in Steam list, Oculus Home detects no HMD, and in SteamVR under the Revive tab, no games show at all. Just a blank screen. 

Oculus is installed to the D: drive, I don't know if that has any bearing on the issue.

**Comment by LibreVR** [comment]
The Oculus update changed some file paths, working on an update now.

**Comment by LibreVR** [comment]
Done: https://github.com/LibreVR/Revive/releases/tag/0.6.1

**Comment by Bender-B-Rodriguez** [comment]
After installing the new update, no games continue to show under the Revive tab in the Virtual Hub of the HTC vive. I have tried reinstalling revive several times and under different folders, with no success. I'll attached a screen shoot. Great work by the way!! 
![untitled](https://cloud.githubusercontent.com/assets/20117858/16322536/92f29598-3958-11e6-91dc-45cce7a4cfc4.jpg)

**Comment by faethon** [comment]
Same here, Revive tab is empty. Updated Oculus Home and reinstalled Revive, but still no luck :(
Hope you find a fix :)

**Comment by LibreVR** [comment]
It looks like these files may have moved to different places for some people. Can you confirm that the folder `C:\Program Files\Oculus\Software\Software` exists for you?

Also go to your Oculus Home Settings > General and confirm that you're running version 1.5.0, maybe you just didn't receive the update yet.

**Comment by faethon** [comment]
Running 1.5.0.240083. 
My Oculus folder is actually in: C:\Program Files (x86)\Oculus\Software
Has the location of the Oculus folder changed? I have it installed since day 1 (have a DK2 as well).

**Comment by LibreVR** [comment]
Wait, your Oculus folder moved to the Software subfolder entirely?

**Comment by faethon** [comment]
This is the folder in which all the installed games are:
C:\Program Files (x86)\Oculus\Software\Software

So for instance, Luckys Tale is in: 
C:\Program Files (x86)\Oculus\Software\Software\playful-luckys-tale

**Comment by LibreVR** [comment]
Ok, that's as expected, can you post the contents of the log files in `%APPDATA%\Revive`?

**Comment by faethon** [comment]
ReviveInjector.log:
```
Launched injector with: D:\Virtual Reality\Vive\Revive\Revive\ReviveInjector_x64.exe /base "Software/playful-luckys-tale/LT.exe"
Creating process: C:\Program Files (x86)\Oculus\Software\playful-luckys-tale\LT.exe
Injecting DLL: D:\Virtual Reality\Vive\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0xf7f174d0
Injecting DLL: D:\Virtual Reality\Vive\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0xf7f174d0
Injected dlls succesfully
```

ReviveOverlay.log:
```
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: D:\Virtual Reality\Vive\Revive\revive.vrmanifest
Runtime directory: file:///D:/Games/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files (x86)/Oculus/
```

Revive and Steam are installed on my D: drive, in the folders as reported in the log files.

**Comment by Bender-B-Rodriguez** [comment]
The location of my Oculus file may be the issue with mine. I have it installed on a separate drive and its location is E:\oculus\software\software

**Comment by LibreVR** [comment]
@faethon That looks fine, but it seems it wasn't able to detect any games. Can you share the contents of `D:\Virtual Reality\Vive\Revive\revive.vrmanifest`?

@Bender-B-Rodriguez That's not a problem, I just gave the default path, but these paths are automatically detected.

**Comment by faethon** [comment]
Contents of the manifest file is indeed rather empty:

```
{
    "applications": [
        {
            "app_key": "revive.dashboard.overlay",
            "arguments": "",
            "binary_path_windows": "ReviveOverlay.exe",
            "image_path": "revive.png",
            "is_dashboard_overlay": true,
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "description": "Revive Dashboard overlay",
                    "name": "Revive Dashboard"
                }
            }
        }
    ]
}

```

**Comment by LibreVR** [comment]
It seems like it can't find the manifest files. What are the contents of `C:\Program Files (x86)\Oculus\Software\Manifests`?

**Comment by Bender-B-Rodriguez** [comment]
Just confirmed that I am running 1.5.0.240083 of the oculus software

**Comment by faethon** [comment]
There is a bunch of json & mini files in that directory, for all the applications I have and had installed. 

I tried reinstalling revive just now, but the manifest file is completely empty now. Probably because I have to run it in Steam. But it's the middle of the night, so have to continue tomorrow.

**Comment by Bender-B-Rodriguez** [comment]
Not sure if this helps, but this is what I got. 
![manf](https://cloud.githubusercontent.com/assets/20117858/16323621/06289690-3961-11e6-8ed2-8a07a115cd86.jpg)

**Comment by Bender-B-Rodriguez** [comment]
Not sure if this helps, but this is what I have in the Manifests file.

![manf](https://cloud.githubusercontent.com/assets/20117858/16323658/5d3b7fe2-3961-11e6-9e1c-95cda0ea0177.jpg)

**Comment by LibreVR** [comment]
@Bender-B-Rodriguez That looks fine, can you post your logs from `%APPDATA%\Revive`?

**Comment by ShadoWallker** [comment]
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-client.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-compat.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-diagnostics.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-dreamdeck-nux.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-drivers.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-home.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-librarian.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-overlays.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-redistributable-installer.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-runtime.json

**Comment by LibreVR** [comment]
I see, it's loading the manifests from the wrong location for some reason. I've reuploaded the installer, can you redownload and reinstall it? Then try if it works and if it doesn't please post your log files again.

**Comment by Bender-B-Rodriguez** [comment]
Here are my logs

libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///E:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///E:/Oculus/

**Comment by LibreVR** [comment]
Yours is just not loading any manifests for some reason...

**Comment by xlapp** [comment]
Having the same issues, was all working before Oculus update today. Installed revive new version and getting a blank page in SteamVR revive overlay. All default install locations, nothing changed

**Comment by xlapp** [comment]
happy to post logs aswell or anything needed

**Comment by LibreVR** [comment]
Log files are the most useful at this point, also try redownloading and reinstalling Revive just to be sure.

**Comment by ShadoWallker** [comment]
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/

**Comment by Bender-B-Rodriguez** [comment]
This is my new log after trying a reinstall, still nothing showing though. The website (github) still shows that the installer was updated 4 hours ago, may the new update hasn't registered on github yet? 


libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///E:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///E:/Oculus/
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-client.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-compat.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-diagnostics.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-dreamdeck-nux.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-drivers.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-home.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-librarian.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-overlays.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-redistributable-installer.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-runtime.json

**Comment by xlapp** [comment]
Re-installed, rebooted

libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/

**Comment by LibreVR** [comment]
Ah I see where this is coming from, I messed up the links in the release description, it was still pointing to the old release while the files at the bottom of the page was correct.

Please redownload and reinstall, it should be alright now.

**Comment by xlapp** [comment]
Brilliant support Libre!

**Comment by LibreVR** [comment]
So it works now?

**Comment by xlapp** [comment]
Re-downloading now, will do another re-boot to be safe and report back in 5

**Comment by xlapp** [comment]
Working perfectly for me, thank you Libre!

**Comment by LibreVR** [comment]
Nice, thanks for the feedback, it's so easy to look over these small mistakes.

**Comment by peteostro** [comment]
apps are now showing up but nothing launches for me

**Comment by LibreVR** [comment]
Please post your log files from `%APPDATA%\Revive`.

**Comment by Bender-B-Rodriguez** [comment]
Sorry to be a pain, but I still get nothing. Now, in addition, the revive icon is not showing. I'll post a screen shot of what I'm doing in a min.

**Comment by LibreVR** [comment]
@Bender-B-Rodriguez It must have shutdown Revive at some point, so just go to your start menu and open Revive Dashboard.

**Comment by peteostro** [comment]
log files
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/331017/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/331018/ReviveOverlay.txt)

**Comment by Bender-B-Rodriguez** [comment]
OK, got icon back but still no games

**Comment by LibreVR** [comment]
Ok, I'm off for today but I'll be back to solve any issues tomorrow, for anyone still experiencing issues try the following:

1. Make sure SteamVR is off.
2. Redownload and reinstall Revive.
3. Reboot the computer, just to be sure.

If it still doesn't work I'll be back to do some more troubleshooting later.

**Comment by Bender-B-Rodriguez** [comment]
Ok, thanks for the help

**Comment by peteostro** [comment]
tried all the suggestions, games do not launch for me

**Comment by Loukey42** [comment]
Mine is not working either, but I noticed something in the log that may help.  Here is my Reviveinjector.log:

Launched injector with: C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/playful-luckys-tale/LT.exe"
Creating process: D:\Oculus\Software\playful-luckys-tale\LT.exe
Failed to create process


Its trying to start D:\Oculus\Software\playful-luckys-tale\LT.exe which doesn't exist.  The file is: D:\Oculus\Software\Software\playful-luckys-tale\LT.exe

**Comment by Loukey42** [comment]
I couldn't get it to work at all, then I completely uninstalled revive and reinstalled and it works fine now.

**Comment by faethon** [comment]
Just tried with the latest version, and everything works again! I had to manually start the Revive dashboard overlay, but since then everything works as expected. The Revive tab is available and contains my games, and I can start them as well (tried Lucky's Tale). Good job!

**Comment by johnnysac5** [comment]
When I click on the link to install version 6.1 on the top of this i get an error 404 page not found message.  Anyone else having this issue?

**Comment by ProfessorS1** [comment]
Same thing as johnnysac. The link to install is an error page. Is there anyway someone could post a link or PM one to me?

Thank you!

**Comment by LibreVR** [comment]
Which link are you using? It may be your virus scanner is blocking the download.

**Comment by ProfessorS1** [comment]
The link at the top of the page that you provided. Is there a newer one?

Thank you
e

**Comment by LibreVR** [comment]
Just to be sure, here's the link again: https://github.com/LibreVR/Revive/releases/download/0.6.2/ReviveInstaller.exe

**Comment by ProfessorS1** [comment]
I had the link to 0.6.1.

Thank you!



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by gormanj** [comment]
So for me the new Oculus setup created a subfolder "software" within the software folder that was in the location of the previous installation. This caused me a bit of confusion when trying place the backup files of my games (software, manifests and redistributables). However once I sorted it out, then the games appeared again in the revive tab.

**Comment by Bender-B-Rodriguez** [comment]
After hours of trying, I finally got it to work. I had to uninstall the Oculus home software, the games and revive. Once I did this and started with a fresh reinstall of everything, it all worked. Kinda of a lot of work, but worth it. Great program, and awesome work LibreVR.

**Comment by LibreVR** [comment]
Your installation of Oculus Home was probably inconsistent, so I think it's a good thing you reinstalled.

Enjoy using Revive!

**Comment by marcob2178** [comment]
hi, i am having the same problem with revive. Blue screen with nothing inside.

Wghere do I get the logfile? I do not see any txt file in %APPDATA%\Revive.

Thanks!

**Comment by lgp1985** [comment]
I had issues because my Oculus installation was made on another drive, so I faked it was in C: with mklink as follows, now it works:
`del "C:\Program Files\Oculus\Software\Manifests"
del "C:\Program Files\Oculus\Software\Software"
mklink /j "C:\Program Files\Oculus\Software\Manifests" "D:\Program Files\Oculus\Software\Manifests"
mklink /j "C:\Program Files\Oculus\Software\Software" "D:\Program Files\Oculus\Software\Software"`
