### ISSUE TITLE
Edge of Nowhere Flickering

### ISSUE THREAD

**Issue by malanthrax** [LibreVR/Revive#182]
I see that a closed issue had this occurring but I am still getting it. Mostly in white areas.

**Comment by LibreVR** [comment]
I made a note in that issue that a potential fix would be part of version 0.8.

**Comment by malanthrax** [comment]
I am confused. Are you saying that, the old issues should have been closed because a possible fix may work at some point, or that this one should be closed because someone reported it in a closed thread? Or that the old one shouldn't be closed?

**Comment by malanthrax** [comment]
Either way do whatever you need if you want to close this one as well.

**Comment by LibreVR** [comment]
Please test the latest release, it may fix this issue.

**Comment by malanthrax** [comment]
Yep will wait for it. Hopefully it fixes it

**Comment by iamwes** [comment]
Still has flickering but its perfectly playable

**Comment by LibreVR** [comment]
I can finally report some progress on this issue. What makes Edge of Nowhere special is that it requests quite a bit of tracking prediction, up to 3 frames into the future. Revive currently only returns the tracking data for the next frame.

It's highly likely that it wants to move certain effects ahead of the direction in which the user is moving his head. Because Revive only gives the data for the next frame these effects are placed in the field of vision of the player instead.

**Comment by LibreVR** [comment]
Nevermind, I was able to reproduce the flickering while keeping the headset completely still so it can't simply be a prediction issue.

**Comment by LibreVR** [comment]
This issue is proving to be difficult, I'll make another attempt for the next version.

**Comment by krysuk** [comment]
Just to tell you ALL your work with revive is amazing and REALLY appreciated
Thanks!

**Comment by JediDiggler** [comment]
Yep, thanks so much. The flickering seems to happen primarily when outside, in the blizzard areas in my experience - dunno if that's any help. Looks like it could be related to the snow particles?

**Comment by tig3rmast3r** [comment]
is it fixed in 1.0 pre? or is it planned for the final 1.0 release? i would like to purchase the game, then i've read compatibilty notes fortunately, thanks for your hard work, dirt rocks!!

**Comment by LibreVR** [comment]
As far as I know it is still not fixed. I would like to fix it before 1.0, but I'm not sure I'll be able to.

**Comment by LibreVR** [comment]
Going to postpone this until 1.1, hopefully I'll have time to look at this soon after the 1.0 release.

**Comment by srt23** [comment]
Its very playable as it is, but will be nice when it is fixed.

**Comment by Armada651** [comment]
Removing the milestone as there is still no adequate way to debug this issue. So far all the graphics debuggers I normally use (apitrace, RenderDoc, VS Graphics Debugger and NSight) crash when attempting to capture a frame in Edge of Nowhere.
