### ISSUE TITLE
Dragon Front not working with Revive

### ISSUE THREAD

**Issue by VRiftist** [LibreVR/Revive#263]
Howdy, just a report that Dragon Front launches to desktop instead of VR. Rebooted machine, latest version of Revive, other games working but not Dragon Front.

**Comment by torsoboy** [comment]
Seeing the same thing here. Got in to the closed beta. Launch the game and it pops up on the desktop for a sec then closes out. I've attached the Revive logs but there doesn't seem to be too much of interest in there.

Thanks in advance!

[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/486402/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/486401/ReviveOverlay.txt)

**Comment by LibreVR** [comment]
The problem is that the Revive dashboard fails to detect the main game executable and injects into the launcher instead. I will update the heuristic in the next version that should fix it.

**Comment by torsoboy** [comment]
That's great to hear. Thanks so much!

**Comment by LibreVR** [comment]
Fixed in commit 40a628c66068cd4a38a2288b41fa3f89f8921c4c.

New version will be released around the end of the week.

**Comment by jtate5** [comment]
I tried version 0.9.5 for this fix.  Unfortunately I still can't open Dragon Front and it seems to have the same behavior as 0.9.0.  Interestingly, I also can no longer launch Damaged Core after this release.  I'm getting a "you have a pending hardware issue that is preventing you from entering vr" error.  

p.s. thanks so much for making this!  You're amazing :)

**Comment by BoomTreble** [comment]
Has anyone been able to make in game purchases? I havent been able to. It just says purchase failed every time

**Comment by LibreVR** [comment]
In-game purchases are a known issue, the problem is that when the game isn't run through Oculus Home (which isn't possible with Revive) it will complain that Oculus Home is in an invalid state.

**Comment by BoomTreble** [comment]
I see. It just seemed that Oculus Home gave some kind of Ok because when I have it open while playing, it does indicate "Now playing Dragon Front" but I guess that doesn't mean all entitlelment checks are passed, just the minimum to start the game and enter matchmaking. Perhaps more strict security checks for purchasing? Oh well, its a super fun game, but not so much when playing against people with customized decks. Well either way, thank you for the recent patch and for the info :)
