### ISSUE TITLE
360 Controller not working (Lucky`s Tail)

### ISSUE THREAD

**Issue by KLWN** [LibreVR/Revive#29]
Hi guys,

I finally got Lucky's Tail up and running, and it look very nice, props to the Dev, great work. Everything works fine except for my 360 controller. The controller works on all my other games except Lucky's Tail. I have setup the controller in the Oculus Home Panel and I can see that its working as indiciated by the green light, but as soon as the game starts I can't "Press A" as requested by the game.

Any advices?

Edit: My setup is Windows 10 Pro, LTpatch 1.0.3, SteamVR, Oculus Home all up-to-date.

greetings,
Alex

**Comment by LibreVR** [comment]
Are you sure it's an Xbox 360 controller and not the Xbox One controller?

**Comment by KLWN** [comment]
yes I am sure :) its connected via Wireless USB Adapter Kit.

**Comment by KLWN** [comment]
seems like new Update on Oculus-Home detects now unavailable Rift and wont start anymore:(

**Comment by hookmanuk** [comment]
I had this problem earlier today. I had another controller plugged in as well as the Xbox controller.

Once I removed the other controller and restarted Lucky's tale it worked fine.

**Comment by gormanj** [comment]
I have an xbox 360 wireless controller and I did not have to run any setup other than the one I did for the whole system (no special oculus setup that I know of). I did find one interesting thing though. Once the driver was installed, I had to find that driver again for every other usb port on my system once and only once. I did not have any issues using it for LT.

**Comment by grantkl** [comment]
I'm also having this issue. Project CARS works perfectly with the 360 controller.

**Comment by nunofgs** [comment]
Also having this issue. Just used the controller in the Oculus Dreamdeck. The X360 controller (with wireless receiver) simply isn't detected in Lucky's tale.

One thing to note is that it IS detected in the Oculus Home settings page.

![capture](https://cloud.githubusercontent.com/assets/92085/14755108/b3d81c4e-08d7-11e6-918b-f901f9fd87dc.PNG)

**Comment by KLWN** [comment]
same here, im on Windows 8.1 Pro. Enabled in Oculus Home but not working in Lucky's Tail

**Comment by LibreVR** [comment]
I can reproduce this issue, I think it's caused by the Lucky's Tale 1.0.3 update, will fix it in the next version.

**Comment by LibreVR** [comment]
Fixed in commit 4e31a5ae724a0b8cd552a70ac12b8cd1e0aef53a. It was a regression in 0.3.

You should be able to use 0.2 with Lucky's Tale until the release of 0.4.

**Comment by grantkl** [comment]
I just tired 0.2 (and the 0.2.1 hotfix) and it still doesn't work

**Comment by tbickle22** [comment]
I can also confirm 360 controller still not working on .2 or .2.1 hotfix 

Win 10 64bit

**Comment by LibreVR** [comment]
Ok, thanks for letting me know. That means the problem only came to surface because of the Lucky's Tale update.

Anyway, the problem should be fixed in 0.4. If you still experience this problem after the release of 0.4 then we can reopen this issue.

**Comment by Kaesemuffin** [comment]
ah okay I thought Xbox one controller was "forced" via the controller dll :D but thanks for your fix maybe this helps with the other games aswell (e.g. Subnautica ^^)

**Comment by LibreVR** [comment]
As an added bonus, version 0.4 will allow you to use your Vive controllers instead of your Xbox controller.

**Comment by aknghiem** [comment]
Hi.

I tried the latest injector, but for some reason, I can't seem to be able to use my Vive controllers with Lucky's Tale (but the injector works great for the game itself though!).

I also tried using the injector with Technolust, but I can no longer use my Xbox controller with it (or the Vive controllers)
