### ISSUE TITLE
Henry is sepia tone

### ISSUE THREAD

**Issue by mcassano** [LibreVR/Revive#3]
Patched with Revive 0.2, the video content plays through from beginning to end but the entire presentation is in a brown sepia tone.

**Comment by mcassano** [comment]
I've been told the Rift turns the scene reddish when it things you have moved out of the scene.  Maybe something about the compatibility layer isn't communicating position properly?

**Comment by mcassano** [comment]
Note that this issue is not resolved in version 0.3 of Revive.  Something of the SDK thinks the headset is out of range of proper seated position so the scene is turned red.  I have tried going into SteamVR and resetting the seated position and I have tried moving the headset in all possible areas of my play area and it is always red (sepia toned).

**Comment by Creep23** [comment]
I just want to second this issue. Seems like it should be fixable if we find the root cause.

**Comment by LibreVR** [comment]
I will take a look at this issue sometime this week.

**Comment by gormanj** [comment]
It may be related to games that show the default Unity down arrow. Graphic. That graphic shows up in a Unity game like "twisted planet dragons" signifying your HMD/Head is raised to high and to lower it (at least that is what I found on the Net about it). In my tests, even when the HMD is set for standing scale and left in the same spot on the floor or raised, as indicated by a post above, Henry and Lost both are monochromatic dark pinkish color.

**Comment by LibreVR** [comment]
Fixed in commit fdb9b9d02782595a423a06572b08d6f1bfd96b9d. Will be part of the next release.

**Comment by OllyTrolly** [comment]
I can't offer any technical insight, but this is still showing as sepia for me in release 0.4. Can anyone else chime in if they're still getting this issue too?

**Comment by mcassano** [comment]
Interesting.  For me it's fixed with 0.4.   Reset your seated position and move your headset all around your tracked space and see it you ever get color.

**Comment by LibreVR** [comment]
@OllyTrolly It's likely that Henry still assumes you have only one tracking base station. Try getting in view of the other base station to see if it detects the headset then.

**Comment by OllyTrolly** [comment]
@LibreVR Ah, that makes a lot of sense then. One of my base stations is FUBAR and needs sending back to HTC, in the mean time I'm able to play certain things with one base station. Obviously, this is a minor bug as I'm sure 99% of the time people will be using both stations, but it still seems like it's worth fixing at some point as the Vive certainly can function with only one base station (you'd be surprised how much works).
