### ISSUE TITLE
Need Noob guide for Dirt Rally on revive for Vive.

### ISSUE THREAD

**Issue by Laerkesen** [LibreVR/Revive#627]
All the guides I find are old.
Also, im a noob when it comes to this, so simple for you might be ?? for me.
Some info said "add new non steam game to steam".. What?? Another info said "unzip reviveinjector" ?? I can only find revive installer?

Here is what I got so far.
Got Vive setup and working. Got SteamVr, got Vive installed.
I ran reviveinstaller 1.1.2, and I installed Rift shop, and I got it to work with games from the rift shop.
Even figured to inject the revive from bottom menu into the rift game exe file to run them. 
Tried to "patch" the game from the Revive Dashboard, but dont really understand this - pushed patch and doubleclicked the Dirt Rally exe file.

But then I hit problems.
Got Dirt Rally on steam. found the folder in steam - but the exe file there don't start Dirt Rally. It only starts with the shortcut that was installed? 
So when I "inject" the Dirt Rally exe file, then nothing happens.

Can someone explain everything step by step in beginner language please? I bought a fckin G29 for this - want to make it work lol.

**Comment by NoobsRUs** [comment]
I hope you can get a response. I am in the same boat here.

**Comment by Armada651** [comment]
@Laerkesen You already did everything correctly, now you just need to start Dirt Rally from Steam, it won't work if you start the exe directly.

**Comment by junkmal333** [comment]
I have a major issue with Dirt Rally , as soon as I patch  and the start up dirt rally from steam I get the message "executable has stopped working. I have installed the latest revive ,also have steam vr Beta ,oculus is installed .Its strange because I had no problems for two months and have not changed my set up. I have even reinstalled the whole PC from scratch to get it to work but still no luck .I really mis my Dirt Rally ,please help.

**Comment by TetsuBo** [comment]
Ran into the same issue.
Patched Dirt Rally executable and when launching I get the message "executable has stopped working".
Downgraded to 1.1.2 and that works fine.

**Comment by junkmal333** [comment]
You are my Hero,

It works again Yesssss ,now I can get my daily dirt rally fix again.

Cheers  Jae

**Comment by Armada651** [comment]
Strange, there were some changes in Version 1.1.3 that attempted to *reduce* instances where Dirt Rally crashed if XInput 1.3 was not installed, seems it achieved the opposite.

What is your operating system?

**Comment by junkmal333** [comment]
W10

**Comment by TetsuBo** [comment]
Win10 64bit, just upgraded to Creators Update.
Have followed the links to download and install the directx redists.

**Comment by Armada651** [comment]
I'll revert the patch and release a hotfix for this issue.

**Comment by junkmal333** [comment]
Super thanks a million :)

Cheers jae

**Comment by Armada651** [comment]
Spotted the error, should be fixed in the latest hotfix. Please re-download the latest version to fix the problem.

**Comment by Skalledalle** [comment]
Thanks Armada! Just got this to work thanks to redownload!

**Comment by andybak** [comment]
The hotfix was 6 days ago but the most recent release (1.1.3) shows as being 10 days ago.

The reason I ask is because I'm still having problems with Dirt Rally.

**Comment by hyperseven** [comment]
>The hotfix was 6 days ago but the most recent release (1.1.3) shows as being 10 days ago.

The reason I ask is because I'm still having problems with Dirt Rally.

is that updated via the app?

**Comment by Armada651** [comment]
@andybak The hotfix replaces the most recent release. The automatic updater should also trigger because the build number is incremented.

**Comment by ghostmanas** [comment]
i have the same problem now... patched it. 
Using revive 1.1.13.0
"Dirt Rally Executable has stopped working"
i tryed everything here.....
pls HELP

**Comment by Dragoboss** [comment]
Please report back if this issue is still going on as-if. Repatch with latest versions, then report.
Thank you.
