### ISSUE TITLE
Pinball FX2 crashes

### ISSUE THREAD

**Issue by peteostro** [LibreVR/Revive#72]
says on the wiki that it works, but it crashes for me

**Comment by gormanj** [comment]
Same here. Access violation. Maybe D3D11. It will launch without revive, but warns of no headset. It starts on the vive with some loading text, but then crashes when first audio is heard.

**Comment by gormanj** [comment]
Unhandled exception at 0x5834BB1A (d3d11.dll) in pfx2vr.exe: 0xC0000005: Access violation reading location 0x00000035.

Exception thrown at 0x5834BB1A (d3d11.dll) in pfx2vr.exe: 0xC0000005: Access violation reading location 0x00000035.

Unhandled exception at 0x5834BB1A (d3d11.dll) in pfx2vr.exe: 0xC0000005: Access violation reading location 0x00000035.

etc.

**Comment by peteostro** [comment]
Also tried running ReviveInjector.exe as admin and did not fix the issue

**Comment by LibreVR** [comment]
I've seen this crash in other applications before, I can probably get it fixed in the next version.

**Comment by LibreVR** [comment]
Please confirm whether this is still an issue in version 0.5.

**Comment by aka4723** [comment]
Yes, the issue persists with 0.5. I also tried all the steps described above.

**Comment by celemis** [comment]
Good morning, I'm from Germany and wanted to know whether pinball fx already works or if it will work soon?

**Comment by bji** [comment]
I just installed Revive and Pinball FX2 VR worked fine.  I do notice that the ball movement doesn't seem as smooth as it did with the DK2, it's like the frame rate is lower, if that's even possible.  I don't notice this apparent reduced frame rate in any other part of the game, just the ball movement.  I do get a slight double image from neon glowing lights when I move my head.  Otherwise, works fine.

**Comment by LibreVR** [comment]
Ok, so not everyone seems to be affected, I will add a crash dump feature in the next release so I can debug crashes.

@bji Those could both be related to timing issues in Revive, which I will try to optimize in the next release. Please make a separate issue report for that.

**Comment by celemis** [comment]
that sounds good, then I will tonight sometimes testen..welcher Revive is the new?

**Comment by thesambassador** [comment]
Not sure if I am seeing the same issue, but I have Pinball FX2 VR and it just launches with a "failed license" error.  After you hit "A" to continue it crashes.

**Comment by LibreVR** [comment]
Should be fixed in 19b9d0f1d04190c4d1eeacd779df26891b00487f.

**Comment by peteostro** [comment]
Thanks so much! Will try it tonight

**Comment by celemis** [comment]
Hi, did it work?

Many greetings

**Comment by peteostro** [comment]
Sorry got sucked into playing Waltz of the wizard, GTA VR + Vive mod an solus project.
Will make an note an try tonight. Before i launch pool nation VR (which I'm sure I'll be lost for hours) So many things to do in VR right now its crazy!

**Comment by celemis** [comment]
nice

**Comment by peteostro** [comment]
Just tried. Game just sits at the loading screen and never loads

**Comment by celemis** [comment]
shame anyway thank you ... I hope for a speedy solution

**Comment by gormanj** [comment]
Tested and working with Revive injector 0.8.3 and Oculus runtime 1.5. Been waiting for this one. Thanks LibreVR!

**Comment by gormanj** [comment]
BTW, if you are looking for a stand to put your arcade stick or keyboard on for pinball, try this one. I got it. It is very sturdy:
https://www.amazon.com/Seville-Classics-WEB162-Mobile-Laptop/dp/B0097GMHXG
