### ISSUE TITLE
No controllers in Robo Recall after V1.5

### ISSUE THREAD

**Issue by Nebuchaddy** [LibreVR/Revive#840]
So.

This is really weird. I cannot make Robo Recall to work in any other version of ReVive other than the latest Third Beta Version 1.2.0

And even if it launches, I can't see or use my vive controllers, so I get stuck on the "Press any button" screen.

The weird thing is, that if turn off any of my controller, Robo Recall will pop up the "No controller" error. 

So, it detects the controllers, but I cnnot use them.

Any wy I cn solve this or is this  known issue?

Any other previoues version that will for sure work with the latest version of Robo Recall? I have it bought so I'm sure ot's the latest (V1.5) version.

Thanks!

**Comment by Armada651** [comment]
> This is really weird. I cannot make Robo Recall to work in any other version of ReVive other than the latest Third Beta Version 1.2.0

So it does work in the third beta version?

**Comment by Nebuchaddy** [comment]
It "works" meaning it laumches, but doesn't recognizes any inputs from my vive controllers, yet warns me that no controllers are on when I turn them off.

**Comment by Armada651** [comment]
Ok so it works in all versions *except* the third beta version? Because your first message says exactly the opposite.

**Comment by dnomyar105** [comment]
Confirmed same problem here. I use the Samsung Odyssey. Beta 2 used to work, but beta 3 does not

**Comment by Nebuchaddy** [comment]
No no no, no versions run the game except the latest third beta version, but in the third beta version, the game launches BUT doesn't recognize the controllers.
So
 Earilier versions: The game wont detect the headset, steamVR wont launch the game and it behaves just like if you bought it from the Oculus store but didnt have a headset (Revive wont "attach" it to SteamVR).
Third Beta Version: The game launches fine with revive BUT the controllers wont work and you get stuck in the "Press any button" screen BUT if you turn off a controller or both, the game will warn you that no controllers are connected.

It is really weird.

**Comment by vraccount** [comment]
Same problem here. HTC Vive
Version 1.1.14 Shown "Headset Error"
Third Beta Version 1.2.0 work but can't play = doesn't recognize vive controllers

P.S. Coco VR work on 1.2.0 Revive Dashboard.

**Comment by elvisbluekite** [comment]
I have Samsung HMD Odyssey

V1.2 worked fine for me. I upgraded to v1.3 and it launches but controllers don't show up. 

Another weird issue: I reinstalled RoboRecall after to see if that helped, now I can't even launch the game, says there is an issue because Entitlements not found.. odd.

**Comment by BeardedSaiyan** [comment]
I had no problems until robo recall updated to version 1.5  the other day with patch notes that say "added Dash Function" or something close to that....... I've tried all 3 versions of revive and like the fine folk above got the farthest with revive v1.3... also tried injecting and patching as well with no luck. Seems to be coming from the robo recall game than the actual driver software... I THINK that something within the games files was added causing the program not to recognize the headset, controllers or censors anymore.

**Comment by Armada651** [comment]
This is a bug in the Revive beta, a workaround is opening and closing the dashboard, that should force the controllers to appear.

**Comment by Nebuchaddy** [comment]
The SteamVR  dashboard or the oculus dashboard. And if so, how do I open the Oculus dashboard from SteamVR?

**Comment by Armada651** [comment]
You really think I meant the Oculus dashboard?

**Comment by Nebuchaddy** [comment]
I was asking because I tried opening the SteamVR dashboard and even though the controllers appear, once I close it the controllers go missing again, so I don't know if I'm missing something :/

**Comment by Armada651** [comment]
I replaced the beta 3 release with one that should fix it: https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3

Do note that Robo Recall doesn't normally show controllers until it asks you to press any button.

**Comment by Nebuchaddy** [comment]
Nope, still wont work. Again, the game launches but can't see or use my controllers. When I open the SteamVR dashboard, the controllers will show up and work fine, but once I go back to the game, again nothing. Maybe it has something to do with the inputs or something?

**Comment by Armada651** [comment]
Which headset are you using? I can't reproduce this on a Vive headset.

**Comment by Legit1337** [comment]
Same Issue here im using the third beta version with htc vive The game launches but no controllers are visible and none of the buttons do anything in the game

**Comment by elvisbluekite** [comment]
No controllers for myself either even on the Press Any Button title screen. I am on Samsung HMD Odyssey. By the way up until this week sometime I was  happily playing Robo Recall on same hardware no problem.

**Comment by DoomDavid** [comment]
Has the opening and closing of the dashboard been successful for anyone in making the controllers re appear in game? Also I seem to have lost the Robo Recall shortcut in the revive dashboard and have to start it by injecting. Anyone else have this issue?

**Comment by Legit1337** [comment]
Closing dashboard how? But Still no controllers after having revive and the game reinstalled.

**Comment by DoomDavid** [comment]
Armada suggestion 2 hours ago about the closing and opening of the vive dashboard

**Comment by Legit1337** [comment]
yeah but how i do that more like where sorry

**Comment by Legit1337** [comment]
OK Nevermind nothing changes controllers dont appear. Sorry i was kinda Brain afk  right now @DoomDavid

**Comment by Armada651** [comment]
I'm able to reproduce it now, seems to be an issue specific to the SteamVR stable.

**Comment by DoomDavid** [comment]
He meant that when you get inside robo recall and  it says to press a button, which you cant because your controllers arent there, to open the vive dashboard with the menu button and to close it. This may make your controllers appear. This was unsuccessful for me.

**Comment by DoomDavid** [comment]
All good Legit lol

**Comment by Legit1337** [comment]
Ok it works for me like that

**Comment by Armada651** [comment]
I've done one more replacement of the beta version: https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3

This time it's fixed for the stable version too.

**Comment by Nebuchaddy** [comment]
Ok!
Now it works, I was using HTC Vive btw. I only had time to test it for a couple of seconds as I need to go to work, but I'll test it later in depth to report if there is any problem.
It looks like it works at the moment.

Thanks @Armada651 !

**Comment by elvisbluekite** [comment]
Will let you know later tonight when I am home to test, thanks in advance @Armada651 !

**Comment by strueli** [comment]
teleportation on the vive controllers seems to work badly now.  it often doesn't recognise touching the touchpad

**Comment by DoomDavid** [comment]
Mine works fine now! For those experiencing bugs like the mission play button not working, just restart the game and it should work. My teleportation @strueli is working fine if not better! remember to SLIDE UP as if you were pressing up on a joystick to teleport. If your touchpad sensors suck and/or if the touchpad doesn't click reference this bro: https://www.reddit.com/r/Vive/comments/4lkkh1/guide_how_to_fix_your_stuck_trackpad_in_the_vive/
https://www.youtube.com/watch?v=PxIQJaWVurs

**Comment by elvisbluekite** [comment]
Quick question, when we upgrade revive, is it best to uninstall the previous version first? Or should we just install right over the existing installation?

**Comment by Nebuchaddy** [comment]
Ok, I have been playing for about 2 hours and the game runs super fine. The new official 360 teleportation update is wonderous for Vive owners.
Again, thanks @Armada651 , keep at it!

**Comment by Toony77** [comment]
Robo recall démarre ,je vois les controlleurs jusque la tout va bien mais quand je charge ma sauvegarde le jeu crash , je suis sur Windows Mixed reality et le jeu fonctionnait bien avant ....
I start with  https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3

**Comment by kiddster** [comment]
Just want to throw my experience in, I cant start the game at all, tried both stable version and beta3 without any luck, it just crashes upon openening, this has been going on since Robo Recall version 1.5.
Also my Arktika.1 is not working either since update 420870, also tried both stable and beta 3, none work.
also tried Antivirus disabled, no luck :( 
Both games crash with this "Oculus hardware issue" - error

**Comment by Pr3DDY** [comment]
Can confirm Robo Recall is definitely working on Vive with latest Beta.

**Comment by Armada651** [comment]
https://github.com/LibreVR/RoboRevive/releases/tag/v1.1
