### ISSUE TITLE
Injector does not work with GZ3Doom

### ISSUE THREAD

**Issue by Glowing0rb** [LibreVR/Revive#94]
I tried to inject Revive into GZ3Doom (and Occulus Rift port for classic Doom), but in vain.
The injectors console window appears and looks fine, however the game just opens in a window and does not get displayed in the headset. Headtracking seems to work though.

**Comment by LibreVR** [comment]
GZ3Doom uses OpenGL, which only has experimental support in Revive right now.

The next version will have improved OpenGL support.

**Comment by LibreVR** [comment]
Fixed in commit db1221756bb317895025ceebea45bc4a6c38dff4.

**Comment by GeePM** [comment]
Still having issues with this, except im not getting any head tracking at all. Tested an Oculous Home game and was able to work perfectly fine there.
