### ISSUE TITLE
using Revive latest release with oculus new patch

### ISSUE THREAD

**Issue by david201275** [LibreVR/Revive#946]
Images from oculus games are missing from revive dashboard in steam

Robo recall is currently unplayable because of extreme lag and jitters. menus seem ok its just when in game.

Not had any issues at all with previous versions of revive.

Windows 10 Pro
Nvidia 980 ti
16Gb RAM
Intel i7 6700K

**Comment by david201275** [comment]
update...
Resolved robo recall issues.
but images from oculus games are missing from revive dashboard in steam.
Just shows a blank box with the executable file name in text

**Comment by Armada651** [comment]
Try downloading the Oculus Setup again and selecting repair: oculus.com/setup

Also make sure you're only using one location for your game library.

**Comment by gormanj** [comment]
I am having the same problem with missing game images. I tried reinstalling Oculus from setup (repair crashed and then had to install) and that did not fix. Going back to Revive 1.2.0 cause the images to reappear.

**Comment by Armada651** [comment]
This is an issue with your setup, all new versions of the Oculus software store their images in `C:\Program Files\Oculus\CoreData\Software\StoreAssets`. If your installation of the Oculus software doesn't do that you should re-install it from scratch.

Implementing support for multiple locations is too much effort for a problem that goes away as people update their software.
