### ISSUE TITLE
Oculus Hardware Detection

### ISSUE THREAD

**Issue by TBonzo** [LibreVR/Revive#960]
Since latest update of Oculus Home I cannot get past the hardware detection in Home setup.
I've tried rebooting, completely removing and re-installing, repairing... everything

I bought The Climb last year (worked great at the time) and now its showing as unplayable until the hardware detection is resolved. The Climb isn't appearing in SteamVR through Revive (I assume because it has to be playable in Oculus Home first).

Anyone else got this issue?
Is there a way of getting round this issue with The Climb?

**Comment by Armada651** [comment]
There should be a skip option in step 3 of the hardware setup.

**Comment by wush3** [comment]
I have the same problem with all oculus games now. Everything worked fine before... now i get a pending hardware issues error at most, the setup has been skipped so that is not it. It seems like they implement a hardware check. Nothing works anymore. I reinstalled SteamVR, Revive and the oculus software stuff then skipped the setup. Did not help.

**Comment by Armada651** [comment]
Found the problem, it's kind of crazy, Oculus misspelled `ovr_SetSynchonizationQueueVk` as `ovr_SetSynchonizationQueueVk` (notice the missing r) in older versions of the Oculus SDK. And because they forced everything to use the new spelling in Oculus SDK 1.24 Revive also switched to the new spelling automatically, which breaks older games that rely on the mispelled version.

Will be fixed in the next version.

**Comment by TBonzo** [comment]
Thanks Jules
Looking forward to getting back on The Climb again

**Comment by bostich83** [comment]
Hi Guys,
are you sure it's fixed with the latest release? I still do get the pending hardware issue message.

@Armada651  can you tell me where this "ovr_SetSynchronizationQueueVk" is misspelled?
I had a quick look at the 5 commits for the last release, and i couldn't find anything regarding that issue.

Thank's!!
//Bostich

**Comment by Armada651** [comment]
It was fixed in commit: 9db7df1117c860b2303322150db7f0aecfef3c00

**Comment by bostich83** [comment]
Thanks for that info @Armada651 

I just made a fresh install with your latest release, i still do get that message (only on the climb).
Iam using HTC-Vive with standard steamvr, nothing modded.

Any ideas?
Regards,
//Bostich

**Comment by TBonzo** [comment]
Installed latest release this evening.
The Climb is still not working for me.

**Comment by Armada651** [comment]
@TBonzo Try running the Oculus Setup and using "repair": https://oculus.com/setup

**Comment by stief300** [comment]
hä #9db7df1 dont know what i should do with that, maybe facebook sucks and let us not anymore play
![hm](https://user-images.githubusercontent.com/38594154/39089036-f16ab8d0-45bd-11e8-9d81-53443a5d2956.JPG)
pls change something, i bought qill and used it only for one day

**Comment by stief300** [comment]
same problem here, already repaired it

**Comment by stief300** [comment]
i think i solved it,, you should install the oculus software somewere else,, not program file

**Comment by TBonzo** [comment]
Cannot get The Climb to work.
Reinstalled and repaired Oculus Home many times (each time is another 5GB download).
I cannot get the Hardware detection error in Oculus Home to go away (I've tried skipping the setup every way I can), and it seems that until Oculus allows play of that game, Revive doesn't add it to the Steam Library.
Thanks for any help you can offer.


![screenshot 1](https://user-images.githubusercontent.com/38137842/39398564-6aad7586-4b07-11e8-917e-1ff1db8c3640.png)

**Comment by Armada651** [comment]
@TBonzo You *cannot* start games from Oculus Home, that never works. What's likely going on is that you have more than one Oculus library and you didn't set your default correctly. See this issue: #928.
